/**
 * Exports a section of the page as a PDF using the browser's print dialog.
 * Clones the target element into a new window with clean styling for print.
 */
export function exportPdf(title: string, elementId: string) {
  const el = document.getElementById(elementId);
  if (!el) return;

  const printWindow = window.open('', '_blank', 'width=900,height=700');
  if (!printWindow) return;

  const escHtml = (s: string) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&#39;');
  const safeTitle = escHtml(title);
  // el.innerHTML is generated by React (auto-escaped). Re-cloning the node preserves that
  // safety without re-introducing any sanitization that could break formatting.
  const safeBody = el.cloneNode(true) as HTMLElement;

  printWindow.document.write(`<!DOCTYPE html>
<html>
<head>
<title>${safeTitle}</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Plus+Jakarta+Sans:wght@600;700;800&display=swap" rel="stylesheet">
<style>
  /* ── Page setup ─────────────────────────────────── */
  @page {
    size: A4;
    margin: 18mm 14mm 20mm 14mm;
    @bottom-right {
      content: "Página " counter(page) " de " counter(pages);
      font-family: 'Inter', sans-serif; font-size: 8.5pt; color: #94a3b8;
    }
    @bottom-left {
      content: "${title.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}";
      font-family: 'Inter', sans-serif; font-size: 8.5pt; color: #94a3b8;
    }
  }
  * { box-sizing: border-box; margin: 0; padding: 0; }
  html, body {
    font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
    font-size: 10pt; color: #0f172a; line-height: 1.55;
    -webkit-font-smoothing: antialiased; text-rendering: optimizeLegibility;
  }
  body { padding: 0; }

  /* ── Typography ──────────────────────────────────── */
  h1, h2, h3 { font-family: 'Plus Jakarta Sans', 'Inter', sans-serif; letter-spacing: -0.01em; color: #0b1220; }
  h1 { font-size: 22pt; font-weight: 800; margin: 0 0 4px; letter-spacing: -0.02em; }
  h2 { font-size: 12pt; font-weight: 700; margin: 32px 0 14px; padding: 0 0 8px; border-bottom: 1.5px solid #e2e8f0;
       text-transform: uppercase; letter-spacing: 0.06em; color: #475569; font-size: 9pt; }
  h3 { font-size: 11pt; font-weight: 700; margin: 22px 0 10px; color: #1e293b; }
  p { margin: 0 0 6px; }
  strong { font-weight: 600; color: #0b1220; }

  /* ── Document header ─────────────────────────────── */
  .pdf-header {
    display: flex; justify-content: space-between; align-items: flex-start;
    padding: 0 0 18px 0; margin: 0 0 24px 0;
    border-bottom: 3px solid #0f172a;
    position: relative;
  }
  .pdf-header::after {
    content: ""; position: absolute; left: 0; bottom: -3px; width: 80px; height: 3px;
    background: linear-gradient(90deg, #0f172a, transparent);
  }
  .pdf-header-meta { text-align: right; font-size: 8.5pt; color: #64748b; line-height: 1.6; }
  .pdf-header-meta strong { color: #0f172a; display: block; font-size: 9pt; margin-bottom: 2px; }
  .pdf-header h1 { margin: 0; }
  .pdf-subtitle { font-size: 9pt; color: #64748b; font-weight: 500; margin-top: 4px; letter-spacing: 0.02em; }

  /* ── Tables (financial style) ────────────────────── */
  table {
    width: 100%; border-collapse: collapse; margin: 0 0 26px 0; font-size: 8.5pt;
    page-break-inside: auto;
  }
  thead { display: table-header-group; }
  tr { page-break-inside: avoid; page-break-after: auto; }
  th {
    text-align: left; font-weight: 600; font-size: 7.5pt; text-transform: uppercase; letter-spacing: 0.05em;
    color: #475569; padding: 10px 12px; background: #f8fafc;
    border-bottom: 1.5px solid #cbd5e1; border-top: 1px solid #e2e8f0;
    white-space: nowrap;
  }
  td {
    padding: 9px 12px; border-bottom: 1px solid #f1f5f9; vertical-align: top;
    color: #1e293b;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
  }
  tbody tr:nth-child(even) td { background: #fafbfc; }
  tbody tr:last-child td { border-bottom: 1px solid #cbd5e1; }
  .text-right { text-align: right; font-variant-numeric: tabular-nums; }

  /* Summary table (Resumo Financeiro) — special styling */
  .pdf-summary-table td {
    padding: 11px 14px; border-bottom: 1px solid #f1f5f9;
    font-size: 9pt;
  }
  .pdf-summary-table td:nth-child(odd) { color: #64748b; font-weight: 500; }
  .pdf-summary-table td:nth-child(even) { font-variant-numeric: tabular-nums; }

  /* ── Section "card" wrapper ──────────────────────── */
  h3 + table, h2 + table { page-break-before: avoid; margin-top: 4px; }
  table + h2 { margin-top: 36px; }
  table + h3 { margin-top: 28px; }

  /* ── Hide noisy inputs/charts ────────────────────── */
  button, [role="tablist"], .recharts-responsive-container, .recharts-wrapper { display: none !important; }
  input, select, textarea { border: none !important; background: transparent !important; padding: 0 !important; }

  /* ── Print fidelity ──────────────────────────────── */
  @media print {
    body { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
    h2, h3 { page-break-after: avoid; }
  }
</style>
</head>
<body>
  <div class="pdf-header">
    <div>
      <h1>${safeTitle}</h1>
      <div class="pdf-subtitle">Documento contabilístico</div>
    </div>
    <div class="pdf-header-meta">
      <strong>Data de exportação</strong>
      ${new Date().toLocaleDateString('pt-PT', { day: '2-digit', month: 'long', year: 'numeric' })}
    </div>
  </div>
  ${safeBody.innerHTML}
</body>
</html>`);

  printWindow.document.close();

  // Wait for content to load then trigger print
  setTimeout(() => {
    printWindow.print();
    // Close window after print dialog closes
    printWindow.onafterprint = () => printWindow.close();
    // Fallback close after delay
    setTimeout(() => { try { printWindow.close(); } catch {} }, 3000);
  }, 500);
}
