project_id = "rfzzrhldukoeuutxsixw"

[auth]
  otp_expiry = 86400

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.manage-access-password]
    verify_jwt = true
  [functions.process-email-queue]
    verify_jwt = true
  [functions.send-transactional-email]
    verify_jwt = false
  [functions.preview-transactional-email]
    verify_jwt = false
  [functions.handle-email-unsubscribe]
    verify_jwt = false
  [functions.handle-email-suppression]
    verify_jwt = false
