GRANT EXECUTE ON FUNCTION public.get_portal_account_manager(uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.get_portal_client_requests(uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.get_portal_comments(uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.get_portal_contract_documents(uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.get_portal_deliverable_file_url(uuid, uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.get_portal_faqs(uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.get_portal_feedback(uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.get_portal_initial_questions(uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.get_portal_meeting_prep_items(uuid, uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.get_portal_meetings(uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.get_portal_monthly_summaries(uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.get_portal_onboarding(uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.get_portal_payment_methods(uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.get_portal_payments(uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.get_portal_phases(uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.get_portal_project_history(uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.get_portal_recurring_occurrences(uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.get_portal_responsibilities(uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.get_portal_routines(uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.portal_add_comment(uuid, text, text) TO anon;
GRANT EXECUTE ON FUNCTION public.portal_add_meeting_notes(uuid, uuid, text) TO anon;
GRANT EXECUTE ON FUNCTION public.portal_add_meeting_prep_item(uuid, uuid, text, text) TO anon;
GRANT EXECUTE ON FUNCTION public.portal_answer_initial_question(uuid, uuid, text, jsonb) TO anon;
GRANT EXECUTE ON FUNCTION public.portal_confirm_meeting(uuid, uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.portal_create_client_request(uuid, text, text) TO anon;
GRANT EXECUTE ON FUNCTION public.portal_delete_meeting_prep_item(uuid, uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.portal_get_recolhas(uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.portal_log_download(uuid, text, text) TO anon;
GRANT EXECUTE ON FUNCTION public.portal_record_visit(uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.portal_submit_feedback(uuid, jsonb) TO anon;
GRANT EXECUTE ON FUNCTION public.portal_submit_initial_questions(uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.portal_submit_nps(uuid, uuid, integer, text, jsonb, jsonb) TO anon;
GRANT EXECUTE ON FUNCTION public.portal_toggle_deliverable(uuid, uuid, boolean) TO anon;
GRANT EXECUTE ON FUNCTION public.portal_toggle_onboarding_step(uuid, uuid, boolean) TO anon;
GRANT EXECUTE ON FUNCTION public.portal_token_active(uuid) TO anon;