CREATE INDEX IF NOT EXISTS idx_tasks_deadline ON public.tasks (deadline);
CREATE INDEX IF NOT EXISTS idx_tasks_status ON public.tasks (status);
CREATE INDEX IF NOT EXISTS idx_tasks_assigned_to ON public.tasks (assigned_to);
CREATE INDEX IF NOT EXISTS idx_commercial_sales_payment_date ON public.commercial_sales (payment_date);
CREATE INDEX IF NOT EXISTS idx_commercial_sales_year_month ON public.commercial_sales (sale_year, sale_month);
CREATE INDEX IF NOT EXISTS idx_financial_expenses_date ON public.financial_expenses (expense_date);
CREATE INDEX IF NOT EXISTS idx_financial_expenses_year_month ON public.financial_expenses (expense_year, expense_month);
CREATE INDEX IF NOT EXISTS idx_content_items_scheduled ON public.content_items (scheduled_at);
CREATE INDEX IF NOT EXISTS idx_meetings_date_time ON public.meetings (date_time);
CREATE INDEX IF NOT EXISTS idx_client_nps_expected_date ON public.client_nps_records (expected_date);
CREATE INDEX IF NOT EXISTS idx_client_milestones_expected_date ON public.client_milestones (expected_date);
CREATE INDEX IF NOT EXISTS idx_time_entries_date ON public.time_entries (entry_date);
CREATE INDEX IF NOT EXISTS idx_crm_leads_status ON public.crm_leads (status);
CREATE INDEX IF NOT EXISTS idx_projects_status ON public.projects (status);
CREATE INDEX IF NOT EXISTS idx_member_payments_status ON public.member_payments (status);
CREATE INDEX IF NOT EXISTS idx_financial_payroll_year_month ON public.financial_payroll (year, month);